name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Build
        run: echo "Build Successful"

      - name: Run Tests
        run: echo "Tests Passed"

      - name: Send Slack Notification
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"✅ CI Pipeline Successful"}' \
          ${{ secrets.SLACK_WEBHOOK }}